/**
 * Skapa array med object i
 * ska funktion för att generera sections
 * Skapa loop i funktioner för att loopa igenom objekten i arrayen
 * Dynamiskt lägga in värden från objekten i varje container
 */

const allproductinformation = [
    {
        id: 1, 
        name: 'Bright & Delicious', 
        price: 3.52, 
        category: 'Vegan', 
        rating: 4, 
        imageURL: 'assets/compressed_photos/bright-and-delicious.png',
        description: '',
        quantity: 0,
    },
    {
        id: 2, 
        name: 'Bloody Strawberry', 
        price: 2.75, 
        category: 'Fruit', 
        rating: 3, 
        imageURL: 'assets/compressed_photos/bloody-strawberry.png',
        description: '',
        quantity: 0,
    },
    {
        id: 3, 
        name: 'Cobnut & Chocolate Amazing', 
        price: 4.85, 
        category: 'Chocolate', 
        rating: 5, 
        imageURL: 'assets/compressed_photos/cobnut-chocolate-and-amazing.png',
        description: '',
        quantity: 0,
    },
    {
        id: 4, 
        name: 'Crispy Chocolate', 
        price: 3.22, 
        category: 'chocolate', 
        rating: 3.5, 
        imageURL: './assets/compressed_photos/crispy-chocolate.png',
        description: '',
        quantity: 0,
    },
    {
        id: 5, 
        name: 'Extra Extra Caramel', 
        price: 4.25, 
        category: 'Caramel', 
        rating: 5, 
        imageURL: 'assets/compressed_photos/extra-extra-caramel.png',
        description: '',
        quantity: 0,
    },
    {
        id: 6, 
        name: 'Les Is More Chocolate', 
        price: 3.45, 
        category: 'Chocolate', 
        rating: 4.5, 
        imageURL: 'assets/compressed_photos/les-is-more-chocolate.png',
        description: '',
        quantity: 0,
    },
    {
        id: 7, 
        name: 'Pink & Still Going Strong', 
        price: 2.58, 
        category: 'Vegan', 
        rating: 4, 
        imageURL: 'assets/compressed_photos/pink-still-going-strong.png',
        description: '',
        quantity: 0,
    },
    {
        id: 8, 
        name: 'Plane But Fabolous', 
        price: 2.85, 
        category: 'Plane', 
        rating: 4.5, 
        imageURL: 'assets/compressed_photos/plane-but-fabolous.png',
        description: '',
        quantity: 0,
    },
    {
        id: 9, 
        name: 'Red Velvet A Match In Heaven', 
        price: 4.84, 
        category: 'Red Velvet', 
        rating: 5, 
        imageURL: 'assets/compressed_photos/red-velvet-match-in-heaven.png',
        description: '',
        quantity: 0,
    },
    {
        id: 10, 
        name: 'Sprinkles All The Way', 
        price: 3.45, 
        category: 'Sprinkles', 
        rating: 4.5, 
        imageURL: 'assets/compressed_photos/sprinkles-all-the-way.png',
        description: '',
        quantity: 0,
    },
];

let cartItems = [];